run_id: "exp002_dk"             # will create runs/exp001/*
dims: 2
paths:
  input_image: "/home/confetti/data/rm009/rm009_roi/z16176_z16300C4_d124_h3500_w5250.tif"
  level: 0   # level and channel are used if input is .ims file
  channel: 1

  output_root: "runs"

  #for ae training
  ae_train_folder: "ae_train"         # buid a dir runs/<run_id>/data/<ae_train_folder>
  ae_test_folder:  "ae_test"           # build a dir runs/<run_id>/data/<ae_test_folder>
  ae_out_folder: "ae_out"              # build a dir runs/<run_id>/<ae_out_folder>
  ae_weight_path: "/home/confetti/e5_workspace/hive1_pipeline/runs/exp001/ae_out/weights/with_last_elu_32_64_96_5_5_3/Epoch_451.pth"
  
  #for feature extraction
  zarr_name: "${autoencoder.ae_exp_name}.zarr"          #save zarr features under  # build a dir runs/<run_id>/data/<zarr_name>
  extract_out_folder: "extract_out"        # logs and configs for feature extraction under runs/<run_id>/<extract_out_folder>

  #for contrastive training
  contrastive_out_folder: "contrastive_out"   # build a dir runs/<run_id>/contrastive_out_folder>
  mlp_weight_path:  

crop:
  roi_size: 64  # size of each roi
  train_split: 0.8  # (0-split )z range will be used in train, and (split,1)z range for test if dims=3, else, along the y axis split the dataset
  split_axis: 1 # 0=Z, 1=Y, 2=X 
  entropy_thres: 2.7  # 2.7 for 4um macaque nissle channel imaging
  amount: 2048  #will sample amount train rois and 0.2*amount test rois
  sample_range:  

autoencoder:
  # New: name each AE training run under this dataset/run_id
  ae_exp_name: "with_last_elu_32_64_96_5_5_3"
  model_name: ae
  encoder_model_name: encoder  # the same arch with encoder in ae, used for step2 feature extraction
  architecture: ae
  block_type:      # block_type can be  'double' 'triple' or empty(will use one conv each layer)
  filters: [32,64,96]  # filters number can not be the same consecutively
  kernel_size: [5,5,3]
  in_channel: 1
  out_channel: 1  #for last channel of decoder, set to 1 for auto input regression
  pad_mode: 'reflect'
  act_mode: 'elu'
  norm_mode: 'none'
  downsample_strategy: 'conv_stride'
  last_layer_act: 'elu' #set none for  auto input regression
  return_bottle_neck: False
  #dataset:
  dataset_name: 'fixed_dataset'
  num_workers: 0
  # loss:
  loss_name: l1 # for ae reconstruction loss
  # trainer:
  trainer_name: 'trainer' #trainer to choose
  save_every: 50 #save frequency
  epoch_num: 500 
  batch_size: 256 
  fp16: false 
  start_epoch: 0
  # solver:
  optimizer: "adam"
  lr_scheduler: "cosine"
  weight_decay: 0.01
  lr_start: 5e-4
  lr_end: 5e-6
  warmup_epochs: 3 

feature_extract:

  # Extract from the WHOLE input image using the trained encoder
  batch_size: 64
  global_offset:  [0,0,0] 
  whole_volume_size:   # if empty, will use the input image size
  region_size:  [64,1536,1536] 
  roi_size:  64 # will be used in all dims
  roi_stride:  16 # will be used in all dims

contrastive_mlp:
  #_______for mlp_encoder_____
  # New: name each contrastive-MLP training run under this dataset/run_id
  contastive_exp_name: "AE${autoencoder.ae_exp_name}_CNTRSTrun1"
  mlp_filters: [96,48,24,12]
  last_encoder: False

  # trainer:
  save_every: 50 #save frequency
  epoch_num: 100
  num_pairs: 16384 
  batch_size: 2048 
  start_epoch: 0
  shuffle_very_epoch: 20 
  valid_very_epoch: 50
  save_very_epoch: 50
  n_views: 2
  pos_topk: False
  pos_weight_ratio: 2
  d_near: 6 # should be decided on input resolution  

  # solver:
  optimizer: "adam"
  lr_scheduler: "cosine"
  weight_decay: 0.01
  lr_start: 5e-4
  lr_end: 5e-6
  lr_warmup: 10


exec:
  use_slurm: False              # true to submit steps via sbatch
  sbatch:
    partition: "compute"
    nodelist: "c003"
    gpus: 1
    cpus_per_task: 8
    mem: "20G"
    time: "24:00:00"
    extra_args: ""             # e.g. "--qos=high"


# show steps
# python pipeline.py -list_steps

# run just the autoencoder (will check tiles exist first)
# python pipeline.py -cfg config/pipeline.yaml -step train_ae

# run just feature extraction (will check AE ckpt + input image)
# python pipeline.py -cfg config/pipeline.yaml -step extract

# force re-run only one step
# python pipeline.py -cfg config/pipeline.yaml -step train_mlp -force

# dry-run (print commands without executing)
# python pipeline.py -cfg config/pipeline.yaml -step crop -dry
