#save_dir
#exp_name is determiend by args.exp_name = f"{args.arch}_linear_prob{args.linear_prob}_batch{args.batch_per_gpu}"
exp_save_dir: "runs/seg_dino"

# system
test_mode: False 
e5: False 
device: cuda
# removed unused: gpu_ids, num_gpus, num_cpus

num_classes: 9

# loss:
supervised_loss: True 

# trainer:
save_every: 5 #save frequency
epochs: 50
valid_very_epoch: 5
# removed unused: trainer_name, save_very_epoch, fp16, tsne_emb

# solver:
lr_start: 5e-4
optimizer: adamw
weight_decay: 1e-4

# dataset:
batch_per_gpu: 16
num_workers: 0
shuffle: true
# removed unused: dataset_name, feats_level, feats_avg_kernel


data_path_dir : "/home/confetti/data/rm009/boundary_seg/new_boundary_seg_data/rois"
mask_path_dir : "/home/confetti/data/rm009/boundary_seg/new_boundary_seg_data/masks"
valid_data_path_dir : "/home/confetti/data/rm009/boundary_seg/new_boundary_seg_data/rois_valid"
valid_mask_path_dir : "/home/confetti/data/rm009/boundary_seg/new_boundary_seg_data/masks_valid"

e5_data_path_dir : "/share/home/shiqiz/data/rm009/boundary_seg/new_boundary_seg_data/rois"
e5_mask_path_dir : "/share/home/shiqiz/data/rm009/boundary_seg/new_boundary_seg_data/masks"
e5_valid_data_path_dir : "/share/home/shiqiz/data/rm009/boundary_seg/new_boundary_seg_data/rois_valid"
e5_valid_mask_path_dir : "/share/home/shiqiz/data/rm009/boundary_seg/new_boundary_seg_data/masks_valid"
make_3ch: False

#model backbone:
arch: 'cmpsd'
# model head:
linear_prob: True # when true, use a single-layer MLP head instead of DPT
# removed unused: recon_target_dir*, bnd_path_dir*

#if None, then do not load any pretrained weights
model_dir : "/home/confetti/e5_workspace/hive1_pipeline/runs/contrastive/onestage_batch2048_nview2_infolossFalse_rm009_4um_mlp[64, 48, 24]/model_epoch_100.pth" 
e5_model_dir: 

#if False, will train the backbone
lock_backbone: True 