exp_name : "test_rm009" #exp_name used to distinguish each run
out: "rm009_ae_out" #path to output directory

# system:
device: cuda
gpu_ids: 0
num_gpus: 1
num_cpus: 2

# model:
#______for cnn_encoder_______
input_size: [64,64,64]
dims : 3
model_name: ae3
architecture: ae
block_type:      # block_type can be  'double' 'triple' or empty(will use one conv each layer)
filters: [32,64,96]  # filters number can not be the same consecutively
kernel_size: [5,5,3]
in_channel: 1
out_channel: 1 
pad_mode: 'reflect'
act_mode: 'elu'
norm_mode: 'none'
#_______for mlp_encoder_____
mlp_filters: [96,48,24,12]
avg_pool_size: [8,8,8] 
avg_pool_padding: False
last_encoder: False

#for seghead
feats_level: 2
feats_avg_kernel: 8
in_channels: 12
num_classes: 8
use_focal: True

# loss:
loss_name: l1 # for ae reconstruction loss 

# trainer:
trainer_name: 'trainer' #trainer to choose
save_every: 50 #save frequency
epoch: 1500
fp16: false 

# solver:
optimizer: "adam"
lr_scheduler_name: "decay"
lr_start: 1e-3
lr_end: 1e-5
weight_decay: 0.01
lr_warmup: 10

# dataset:
e5: False 
dataset_name: 'simple_dataset'
batch_per_gpu: 256 
num_workers: 0
shuffle: true

data_path_dir: "/home/confetti/data/rm009/v1_roi1_seg/l2_pool8_aemlpv1_continue_e7500"
mask_path_dir: "/home/confetti/data/rm009/v1_roi1_seg/masks"
valid_data_path_dir: "/home/confetti/data/rm009/v1_roi1_seg_valid/l2_pool8_aemlpv1_continue_e7500"
valid_mask_path_dir: "/home/confetti/data/rm009/v1_roi1_seg_valid/masks"

# e5_data_path_dir: "/share/home/shiqiz/data/rm009/v1_roi1_seg/l2_pool8_aemlpv1_continue_e7500"
# e5_mask_path_dir: "/share/home/shiqiz/data/rm009/v1_roi1_seg/masks"
# e5_valid_data_path_dir: "/share/home/shiqiz/data/rm009/v1_roi1_seg_valid/l2_pool8_aemlpv1_continue_e7500"
# e5_valid_mask_path_dir: "/share/home/shiqiz/data/rm009/v1_roi1_seg_valid/masks"



#for mlp contrastive_learning
num_epochs: 4000
num_pairs: 16384 
start_epoch: 0
batch_size: 8 
shuffle_very_epoch: 50 
valid_very_epoch: 20
save_very_epoch: 50
n_views: 4 
pos_weight_ratio: 2
# raw_img: 4um  feats_map: 16stride --> 64 um resol in feats_map
d_near: 4 
loss_enhance: True 
re_use: False 
exp_save_dir: "outs/contrastive_run_rm009"

